---
title: "The normal distribution"
---

This vignette uses the following packages:

```{r}
pacman::p_load(tidyverse, car, SimDesign, regclass)
```

The normal distribution, often referred to as the "bell curve" due to its characteristic shape, is a fundamental concept in the realm of statistics and is highly pertinent in psychological research. This distribution is defined by two parameters: its mean (µ) and its standard deviation (σ).

**Important Properties:**

- Symmetrical: The left half of the curve is a mirror image of the right half.
- Bell-shaped: It peaks at the mean and tapers off towards the tails.
- Mean, median, and mode are all equal and located at the center of the distribution.

  
## Why is the Normal Distribution Important in Psychology?

The normal distribution is important for a number of reasons.

**Central Limit Theorem (CLT)**: Regardless of the shape of the population distribution, the sampling distribution of the sample mean approaches a normal distribution as the sample size grows. This provides the theoretical basis for many statistical procedures used in psychological research.
Standard Scores (Z-scores): Allow researchers to determine how unusual a particular score is within a distribution.
Parametric Tests: Many statistical tests (e.g., t-tests, ANOVA) have an assumption of normality, which means they assume that the data is normally distributed.

The Gaussian distribution, also known as the normal distribution, is described by the following probability density function (pdf):

$f(x|\mu,\sigma^2) = \frac{1}{\sigma \sqrt{2\pi}} e^{-\frac{(x-\mu)^2}{2\sigma^2}}$

Where:

- $x$ is a variable.
- $\mu$ is the mean of the distribution.
- $\sigma$ is the standard deviation of the distribution.
- $\sigma^2$ is the variance of the distribution.
- $e$ is the base of the natural logarithm (approximately equal to 2.71828).

The equation describes the characteristic "bell-shaped" curve of the normal distribution. The peak of the curve is at the mean $\mu$, and the width of the bell is determined by the standard deviation $\sigma$. The factor $\frac{1}{\sigma \sqrt{2\pi}}$ ensures that the total area under the curve is equal to 1, which is a property of probability density functions.